# Generated by Django 3.1.7 on 2021-04-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210416_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='images/userpic.png', max_length=300),
        ),
    ]
