# Generated by Django 3.1.7 on 2021-04-29 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='_user_followed_by_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
