# Generated by Django 3.1.7 on 2021-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_followed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
