# Generated by Django 3.1.7 on 2021-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210310_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ends',
            field=models.DateTimeField(),
        ),
    ]
