# Generated by Django 3.1.7 on 2021-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210310_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startprice',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
