# Generated by Django 3.1.7 on 2021-03-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210311_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ends',
            field=models.DateTimeField(null=True),
        ),
    ]
