# Generated by Django 3.1.7 on 2021-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210311_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.CharField(default='yes', max_length=3),
        ),
    ]
