# Generated by Django 3.1.7 on 2021-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentprice',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
