# Generated by Django 3.2.4 on 2021-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'free'), (6, 'silver'), (9, 'gold')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'cashier'), (6, 'supervisor'), (9, 'Acccount Manager')], null=True),
        ),
    ]
