# Generated by Django 3.2.4 on 2021-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20210615_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_manager',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'cashier'), (6, 'supervisor'), (9, 'Account Manager')], null=True),
        ),
    ]
