# Generated by Django 3.2.4 on 2021-06-16 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cashiers',
            field=models.ManyToManyField(blank=True, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='POS.store'),
        ),
    ]
