# Generated by Django 3.2.4 on 2021-06-18 01:54

import POS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_auto_20210616_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=POS.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
