# Generated by Django 3.2.4 on 2021-06-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_alter_inventory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
