# Generated by Django 3.2.4 on 2021-06-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_alter_inventory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
