# Generated by Django 3.2.4 on 2021-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_auto_20210620_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
