# Generated by Django 3.2.4 on 2021-06-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0016_alter_transactions_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
