# Generated by Django 3.2.4 on 2021-06-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0019_auto_20210629_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='POS.inventory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='POS.register'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='POS.store'),
        ),
        migrations.DeleteModel(
            name='NewTransaction',
        ),
    ]
