# Generated by Django 3.2.4 on 2021-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0021_auto_20210629_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='register',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
