# Generated by Django 3.2.4 on 2021-07-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0023_auto_20210629_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.CharField(max_length=30)),
                ('status', models.PositiveSmallIntegerField(choices=[(9, 'in'), (3, 'out')])),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashlog', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashlog', to='POS.register')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashlog', to='POS.store')),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='POS.Inventory'),
        ),
        migrations.DeleteModel(
            name='Cashlog',
        ),
    ]
