# Generated by Django 3.2.4 on 2021-07-21 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0024_auto_20210714_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='amount',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='movement',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reciept',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
