# Generated by Django 3.2.4 on 2021-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0025_auto_20210721_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='reciept',
        ),
        migrations.AddField(
            model_name='transactions',
            name='reciept',
            field=models.ManyToManyField(blank=True, related_name='transaction', to='POS.Reciept'),
        ),
    ]
