# Generated by Django 3.2.4 on 2021-07-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0026_auto_20210723_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='status',
            new_name='text',
        ),
    ]
